### ISSUE TITLE
How to visualize test example

### ISSUE THREAD

**Issue by FrankSinatral** [ruiqini/NTFields#1]
Thanks for your great work! And I am wondering how to visualize your test examples (including box and bunny) in your paper! Thanks~

**Comment by ruiqini** [comment]
Thank you for your interests, you can run 
```eval
python test/gib_plan.py 
``` 
to visualize our Gibson example. We didn’t provide pretrained model for bunny and box, and you can train it yourself and visualize them in the same way with Gibson.

**Comment by FrankSinatral** [comment]
Are there codes for running the FMM method on box and bunny environments?

**Comment by ruiqini** [comment]
No, we don’t include FMM in our code, you can use any FMM library. We used pykonal https://github.com/malcolmw/pykonal.
